### ISSUE TITLE
GitHub Sponsorship

### ISSUE THREAD

**Issue by nathanclevenger** [helloimalastair/FlareUtils#2]
[Drivly](https://github.com/drivly) would like to sponsor FlareUtils.  @helloimalastair would you be open to that?

We offer simple unified APIs to buy and sell cars online, and we're funded by some of the [biggest names](https://twitter.com/TurnerNovak) in [automotive](https://fontinalis.com/team/#bill-ford) and [finance & insurance](https://www.detroit.vc)

Our entire infrastructure is also built on Cloudflare Workers, and we're using FlareUtils extensively.

**Comment by helloimalastair** [comment]
Thank you again for your sponsorship, Nathan!
