### ISSUE TITLE
BetterKV still hits a lot of KV.get

### ISSUE THREAD

**Issue by lavrton** [helloimalastair/FlareUtils#6]
Hello. I have several questions, all of them around one issue. So I am using BetterKV and I noticed that I don't see much reduction in KV read usage.

Question about line:

https://github.com/helloimalastair/FlareUtils/blob/b223d82853e1c0773b6028e73f74066f085e53e8/src/BetterKV/index.ts#L148

Isn't there an issue in ms vs secs metrics? `cacheTtl` is in secs, right? Looks like it will make `Math.random() < probability` always true, which will lead to reading from cache.

Here shouldn't we try to use `expirationTtl` from options when we set a key/value?

https://github.com/helloimalastair/FlareUtils/blob/b223d82853e1c0773b6028e73f74066f085e53e8/src/BetterKV/index.ts#L344

**Comment by helloimalastair** [comment]
@lavrton how is [this](https://github.com/helloimalastair/FlareUtils/pull/7) for your first issue?

As for the second thing, while it would be more efficient, I don't think it actually hurts anything to cache longer, since we check for expiration with the probability check anyway?
